language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget http://selenium-release.storage.googleapis.com/2.43/selenium-server-standalone-2.43.1.jar
  - java -jar selenium-server-standalone-2.43.1.jar -port 4444 &
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - chmod +x ./ci_script

script: ./ci_script
